SELECT COUNT(*) FROM CLIENTE;
SELECT COUNT(*) FROM EMPLEADO;
SELECT COUNT(*) FROM TIENDA;
SELECT COUNT(*) FROM PAGO_EMPLEADO;
SELECT COUNT(*) FROM PELICULA;
SELECT COUNT(*) FROM ACTOR;
SELECT COUNT(*) FROM CATEGORIA;
SELECT COUNT(*) FROM RENTAS;