DROP TABLE IF EXISTS CSV_DATA;

CREATE TABLE CSV_DATA (

    id SERIAL,
    NOMBRE_CLIENTE VARCHAR(300),
    CORREO_CLIENTE VARCHAR(300),
    CLIENTE_ACTIVO VARCHAR(300),
    FECHA_CREACION VARCHAR(300),
    TIENDA_PREFERIDA VARCHAR(300),
    DIRECCION_CLIENTE VARCHAR(300),
    CODIGO_POSTAL_CLIENTE VARCHAR(300),
    CIUDAD_CLIENTE VARCHAR(300),
    PAIS_CLIENTE VARCHAR(300),
    FECHA_RENTA VARCHAR(300),
    FECHA_RETORNO VARCHAR(300),
    MONTO_A_PAGAR VARCHAR(300),
    FECHA_PAGO VARCHAR(300),
    NOMBRE_EMPLEADO VARCHAR(300),
    CORREO_EMPLEADO VARCHAR(300),
    EMPLEADO_ACTIVO VARCHAR(300),
    TIENDA_EMPLEADO VARCHAR(300),
    USUARIO_EMPLEADO VARCHAR(300),
    CONTRASEÑA_EMPLEADO VARCHAR(300),
    DIRECCION_EMPLEADO VARCHAR(300),
    CODIGO_POSTAL_EMPLEADO VARCHAR(300),
    CIUDAD_EMPLEADO VARCHAR(300),
    PAIS_EMPLEADO VARCHAR(300),
    NOMBRE_TIENDA VARCHAR(300),
    ENCARGADO_TIENDA VARCHAR(300),
    DIRECCION_TIENDA VARCHAR(300),
    CODIGO_POSTAL_TIENDA VARCHAR(300),
    CIUDAD_TIENDA VARCHAR(300),
    PAIS_TIENDA VARCHAR(300),
    TIENDA_PELICULA VARCHAR(300),
    NOMBRE_PELICULA VARCHAR(300),
    DESCRIPCION_PELICULA VARCHAR(300),
    AÑO_LANZAMIENTO VARCHAR(300),
    DIAS_RENTA VARCHAR(300),
    COSTO_RENTA VARCHAR(300),
    DURACION VARCHAR(300),
    COSTO_POR_DAÑO VARCHAR(300),
    CLASIFICACION VARCHAR(300),
    LENGUAJE_PELICULA VARCHAR(300),
    CATEGORIA_PELICULA VARCHAR(300),
    ACTOR_PELICULA VARCHAR(300),
    
    PRIMARY KEY (id)

);

/*ubicacion debera ser cambiada de ser necesario*/
COPY CSV_DATA(NOMBRE_CLIENTE,CORREO_CLIENTE,CLIENTE_ACTIVO,FECHA_CREACION,TIENDA_PREFERIDA,DIRECCION_CLIENTE,CODIGO_POSTAL_CLIENTE,CIUDAD_CLIENTE,PAIS_CLIENTE,FECHA_RENTA,FECHA_RETORNO,MONTO_A_PAGAR,FECHA_PAGO,NOMBRE_EMPLEADO,CORREO_EMPLEADO,EMPLEADO_ACTIVO,TIENDA_EMPLEADO,USUARIO_EMPLEADO,CONTRASEÑA_EMPLEADO,DIRECCION_EMPLEADO,CODIGO_POSTAL_EMPLEADO,CIUDAD_EMPLEADO,PAIS_EMPLEADO,NOMBRE_TIENDA,ENCARGADO_TIENDA,DIRECCION_TIENDA,CODIGO_POSTAL_TIENDA,CIUDAD_TIENDA,PAIS_TIENDA,TIENDA_PELICULA,NOMBRE_PELICULA,DESCRIPCION_PELICULA,AÑO_LANZAMIENTO,DIAS_RENTA,COSTO_RENTA,DURACION,COSTO_POR_DAÑO,CLASIFICACION,LENGUAJE_PELICULA,CATEGORIA_PELICULA,ACTOR_PELICULA)
FROM '/home/kaliwsl/Desktop/MIA_Practica1_20161233_2021_2S/BlockbusterData.csv' 
DELIMITER ';'
CSV HEADER ENCODING 'latin1'; /*latin1 es el encode para que admita valores en espanol*/


SELECT COUNT(*) FROM CSV_DATA;

/*SELECT NOMBRE_CLIENTE FROM CSV_DATA;*/