DROP TABLE IF EXISTS RENTAS;
DROP SEQUENCE IF EXISTS RENTAS_SEQ;
DROP TABLE IF EXISTS TIENDA;
DROP TABLE IF EXISTS PAGO_EMPLEADO;
DROP SEQUENCE IF EXISTS PAGO_EMPLEADO_seq;
DROP TABLE IF EXISTS ACTOR;
DROP SEQUENCE IF EXISTS ACTOR_SEQ ;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS EMPLEADO;
  
DROP TABLE IF EXISTS PELICULA;

DROP TABLE IF EXISTS CATEGORIA;
DROP SEQUENCE IF EXISTS CATEGORIA_SEQ;


---CARGA DE DATOS CLIENTE
CREATE TABLE CLIENTE (
  NOMBRE_CLIENTE VARCHAR(150) NULL DEFAULT NULL,
  
  CORREO_CLIENTE VARCHAR(255) NOT NULL DEFAULT NULL,
  DIRECCION_CLIENTE VARCHAR(300) NULL DEFAULT NULL,
  FECHA_CREACION DATE NULL,
  CLIENTE_ACTIVO VARCHAR(2) NULL DEFAULT NULL,
  CODIGO_POSTAL_CLIENTE VARCHAR(20) NULL DEFAULT NULL,
  CIUDAD_CLIENTE VARCHAR(150) NULL DEFAULT NULL,
  PAIS_CLIENTE VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (CORREO_CLIENTE)
);


INSERT INTO CLIENTE 
SELECT DISTINCT NOMBRE_CLIENTE, CORREO_CLIENTE, DIRECCION_CLIENTE, TO_DATE(FECHA_CREACION,'DD/MM/YYYY'), CLIENTE_ACTIVO,CODIGO_POSTAL_CLIENTE,CIUDAD_CLIENTE,PAIS_CLIENTE
FROM CSV_DATA
WHERE FECHA_CREACION != '-'  ;

---CARGA DE DATOS EMPLEADO



CREATE TABLE EMPLEADO(
  NOMBRE_EMPLEADO VARCHAR(150) NULL DEFAULT NULL,
  DIRECCION_EMPLEADO VARCHAR(255) NULL DEFAULT NULL,
  CORREO_EMPLEADO VARCHAR(255) NULL DEFAULT NULL,
  EMPLEADO_ACTIVO VARCHAR(2) NULL DEFAULT NULL,
  USUARIO_EMPLEADO VARCHAR(150) NULL DEFAULT NULL,
  CONTRASEÑA_EMPLEADO VARCHAR(150) NULL DEFAULT NULL,
  TIENDA_EMPLEADO VARCHAR(150) NULL DEFAULT NULL,
  CIUDAD_EMPLEADO VARCHAR(150) NULL DEFAULT NULL,
  PAIS_EMPLEADO VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (USUARIO_EMPLEADO)
);

INSERT INTO EMPLEADO
SELECT DISTINCT NOMBRE_EMPLEADO, DIRECCION_EMPLEADO, CORREO_EMPLEADO, EMPLEADO_ACTIVO, USUARIO_EMPLEADO, CONTRASEÑA_EMPLEADO, TIENDA_EMPLEADO, CIUDAD_EMPLEADO, PAIS_EMPLEADO
FROM CSV_DATA
WHERE USUARIO_EMPLEADO != '-' ;

--CARGA DE DATOS TIENDA



CREATE TABLE TIENDA(
  
  NOMBRE_TIENDA VARCHAR(50) NULL DEFAULT NULL,
  DIRECCION_TIENDA VARCHAR(255) NULL DEFAULT NULL,
  
  CIUDAD_TIENDA VARCHAR(150) NULL DEFAULT NULL,
  PAIS_TIENDA VARCHAR(150) NULL DEFAULT NULL,
  ENCARGADO_TIENDA VARCHAR(150) NULL DEFAULT NULL,

  PRIMARY KEY(NOMBRE_TIENDA,DIRECCION_TIENDA)
);





INSERT INTO TIENDA
SELECT DISTINCT NOMBRE_TIENDA, DIRECCION_TIENDA, CIUDAD_TIENDA, PAIS_TIENDA, USUARIO_EMPLEADO
FROM CSV_DATA
WHERE ENCARGADO_TIENDA != '-'
;

--CARGA DE DATOS PAGO_EMPLEADO


CREATE SEQUENCE PAGO_EMPLEADO_seq;

CREATE TABLE PAGO_EMPLEADO(
  ID INTEGER NOT NULL DEFAULT NEXTVAL ('PAGO_EMPLEADO_seq'),
  MONTO_A_PAGAR FLOAT NULL DEFAULT NULL,
  FECHA_PAGO DATE NULL,
  USUARIO_EMPLEADO VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO PAGO_EMPLEADO (MONTO_A_PAGAR,FECHA_PAGO,USUARIO_EMPLEADO)
SELECT TO_NUMBER(MONTO_A_PAGAR ,'99G999D9S'), TO_TIMESTAMP(FECHA_PAGO, 'DD/MM/YYYY HH24:MI:SS'), USUARIO_EMPLEADO
FROM CSV_DATA
WHERE MONTO_A_PAGAR !='-';

CREATE TABLE PELICULA(
  NOMBRE_PELICULA VARCHAR(150) NULL DEFAULT NULL,
  DESCRIPCION_PELICULA VARCHAR(350) NULL DEFAULT NULL,
  AÑO_LANZAMIENTO DATE NULL DEFAULT NULL,
  DURACION INTEGER NULL DEFAULT NULL,
  DIAS_RENTA INTEGER NULL DEFAULT NULL,
  COSTO_RENTA FLOAT NULL DEFAULT NULL,
  COSTO_POR_DAÑO FLOAT NULL DEFAULT NULL,
  CLASIFICACION VARCHAR(10) NULL DEFAULT NULL,
  LENGUAJE_PELICULA VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (NOMBRE_PELICULA,AÑO_LANZAMIENTO,LENGUAJE_PELICULA)
);

INSERT INTO PELICULA
SELECT DISTINCT NOMBRE_PELICULA, DESCRIPCION_PELICULA,TO_DATE(AÑO_LANZAMIENTO,'YYYY'), TO_NUMBER(DURACION,'99G999D9S'),TO_NUMBER(DIAS_RENTA,'99G999D9S'),TO_NUMBER(COSTO_RENTA,'99G999D9S'), TO_NUMBER(COSTO_POR_DAÑO,'99G999D9S'),CLASIFICACION,LENGUAJE_PELICULA
FROM CSV_DATA
WHERE AÑO_LANZAMIENTO != '-'
;

CREATE SEQUENCE ACTOR_SEQ;
CREATE TABLE ACTOR(
  ID INTEGER NOT NULL DEFAULT NEXTVAL('ACTOR_SEQ'),
  NOMBRE_PELICULA VARCHAR(150) NOT NULL,
  ACTOR_PELICULA VARCHAR(150) NOT NULL,
  PRIMARY KEY(ID)
);

INSERT INTO ACTOR(NOMBRE_PELICULA, ACTOR_PELICULA)
SELECT NOMBRE_PELICULA, ACTOR_PELICULA
FROM CSV_DATA
WHERE ACTOR_PELICULA !='-';

CREATE SEQUENCE CATEGORIA_SEQ;
CREATE TABLE CATEGORIA(
  ID INTEGER NOT NULL DEFAULT NEXTVAL('CATEGORIA_SEQ'),
  NOMBRE_PELICULA VARCHAR(150) NOT NULL,
  CATEGORIA_PELICULA VARCHAR(150) NOT NULL,
  PRIMARY KEY(ID)
);

INSERT INTO CATEGORIA(NOMBRE_PELICULA,CATEGORIA_PELICULA)
SELECT DISTINCT NOMBRE_PELICULA, CATEGORIA_PELICULA
FROM CSV_DATA
WHERE NOMBRE_PELICULA!='-';

CREATE SEQUENCE RENTAS_SEQ;
CREATE TABLE RENTAS(
  ID INTEGER NOT NULL DEFAULT NEXTVAL('RENTAS_SEQ'),
  CORREO_CLIENTE VARCHAR(255) NOT NULL,
  FECHA_RENTA DATE NOT NULL,
  FECHA_RETORNO VARCHAR(250) NOT NULL,
  MONTO_A_PAGAR FLOAT NOT NULL,
  USUARIO_EMPLEADO VARCHAR(150) NOT NULL,
  NOMBRE_PELICULA VARCHAR(150) NOT NULL,
  TIENDA_PREFERIDA VARCHAR(150) NOT NULL,
  PRIMARY KEY(ID)

);

INSERT INTO RENTAS(CORREO_CLIENTE,FECHA_RENTA,FECHA_RETORNO,MONTO_A_PAGAR,USUARIO_EMPLEADO,NOMBRE_PELICULA, TIENDA_PREFERIDA)
SELECT CORREO_CLIENTE, TO_TIMESTAMP(FECHA_RENTA, 'DD/MM/YYYY HH24:MI:SS'), (FECHA_RETORNO), TO_NUMBER(MONTO_A_PAGAR,'99G999D9S'),USUARIO_EMPLEADO,NOMBRE_PELICULA, TIENDA_PREFERIDA
FROM CSV_DATA
WHERE FECHA_RENTA !='-';


---LLAVES FORANEAS
ALTER TABLE TIENDA ADD FOREIGN KEY (ENCARGADO_TIENDA) REFERENCES EMPLEADO (USUARIO_EMPLEADO);
ALTER TABLE PAGO_EMPLEADO ADD FOREIGN KEY (USUARIO_EMPLEADO) REFERENCES EMPLEADO (USUARIO_EMPLEADO);
ALTER TABLE RENTAS ADD FOREIGN KEY (CORREO_CLIENTE) REFERENCES CLIENTE(CORREO_CLIENTE);
ALTER TABLE RENTAS ADD FOREIGN KEY (USUARIO_EMPLEADO) REFERENCES EMPLEADO(USUARIO_EMPLEADO);
--ALTER TABLE CATEGORIA ADD FOREIGN KEY(NOMBRE_PELICULA) REFERENCES PELICULA (NOMBRE_PELICULA,A);
--ALTER TABLE ACTOR ADD FOREIGN KEY (NOMBRE_PELICULA) REFERENCES PELICULA (NOMBRE_PELICULA);
--SELECT * FROM CLIENTE;
--SELECT * FROM EMPLEADO
--SELECT * FROM TIENDA;
--SELECT * FROM PAGO_EMPLEADO
--SELECT * FROM PELICULA
--SELECT * FROM ACTOR
--SELECT * FROM CATEGORIA
--SELECT * FROM RENTAS


