--MOSTRAR LA CANTIDAD DE COPIAS QUE EXISTEN EN EL INVENTARIO PARA LA PELICULA SUGAR WONKA
--PSEUDO SELECT COUNT(*) FROM RENTAS WHERE NOMBRE_PELICULA = SUGAR WONKA AND FECHA_RETORNO != '-'
SELECT COUNT(*) AS EXISTENCIAS   FROM RENTAS 
WHERE NOMBRE_PELICULA = 'SUGAR WONKA';