DROP TABLE IF EXISTS CLIENTE;
		

CREATE TABLE CLIENTE (
  NOMBRE_CLIENTE VARCHAR(150) NULL DEFAULT NULL,
  
  CORREO_CLIENTE VARCHAR(255) NOT NULL DEFAULT NULL,
  DIRECCION_CLIENTE VARCHAR(300) NULL DEFAULT NULL,
  FECHA_CREACION DATE NULL,
  CLIENTE_ACTIVO VARCHAR(2) NULL DEFAULT NULL,
  CODIGO_POSTAL_CLIENTE VARCHAR(20) NULL DEFAULT NULL,
  CIUDAD_CLIENTE VARCHAR(150) NULL DEFAULT NULL,
  PAIS_CLIENTE VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (CORREO_CLIENTE)
);


INSERT INTO CLIENTE 
SELECT DISTINCT NOMBRE_CLIENTE, CORREO_CLIENTE, DIRECCION_CLIENTE, TO_DATE(FECHA_CREACION,'DD/MM/YYYY'), CLIENTE_ACTIVO,CODIGO_POSTAL_CLIENTE,CIUDAD_CLIENTE,PAIS_CLIENTE
FROM CSV_DATA
WHERE FECHA_CREACION != '-'  ;




SELECT * FROM CLIENTE;